# Generated by Django 3.0.3 on 2020-04-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.IntegerField(verbose_name='确诊')),
                ('dead', models.IntegerField(verbose_name='死亡')),
                ('heal', models.IntegerField(verbose_name='治愈')),
                ('time_info', models.DateTimeField(verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '今日总体数据',
                'verbose_name_plural': '今日总体数据',
            },
        ),
        migrations.CreateModel(
            name='MXInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, verbose_name='省')),
                ('name', models.CharField(max_length=50, verbose_name='市')),
                ('confirm', models.IntegerField(verbose_name='确诊')),
                ('suspect', models.IntegerField(verbose_name='疑似')),
                ('dead', models.IntegerField(verbose_name='死亡')),
                ('heal', models.IntegerField(verbose_name='治愈')),
                ('time_info', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '各省信息',
                'verbose_name_plural': '各省信息',
            },
        ),
    ]
