# Generated by Django 3.0.3 on 2020-04-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allinfo',
            old_name='qz',
            new_name='confirm',
        ),
        migrations.RenameField(
            model_name='allinfo',
            old_name='se',
            new_name='dead',
        ),
        migrations.RenameField(
            model_name='allinfo',
            old_name='zy',
            new_name='heal',
        ),
    ]
